Refactor for new Nimble structure, add readBody proc, add more docs
philip-wernersbach/microasynchttpserver pull request #1
Opened 2023-04-13 05:31 UTC by termermc

This PR depends on my other PR on `nim-picohttpparser`, don't approve this PR until that one is merged.

There's no need for manually including the picohttpparser in this version due to the other PR.
Other than refactoring the code, this adds a proc called `readBody` which reads the request body into memory and returns it.

It also adds a simple test.

2023-04-14 18:21 UTC, philip-wernersbach commented
Thank you for your work on this, and your contribution! I will review both PR's this weekend.

2023-04-16 01:58 UTC, philip-wernersbach requested changes

2023-04-16 01:58 UTC, philip-wernersbach commented on README.md
> -   [picohttpparser.c](https://github.com/h2o/picohttpparser/blob/master/picohttpparser.c).
Question: What's the recommended way to install this now? Nimble?

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +    return res
Use `result` and the new `ref` object instantiation syntax (if it doesn't work, you might have to change MicroAsyncHttpServer to a `ref object`):
```suggestion
    result = MicroAsyncHttpServer(newAsyncSocket())
```

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +const badRequestHttpResponse = "HTTP/1.1 400 Bad Request\r\nExpires: Thu, 01 Jan 1970 00:00:01 GMT\r\nContent-Length: 0\r\n\r\n"
Use `HTTP/1.0` here, both HTTP 1.0 and 1.1 clients understand it:
```suggestion
const badRequestHttpResponse = "HTTP/1.0 400 Bad Request\r\nExpires: Thu, 01 Jan 1970 00:00:01 GMT\r\nContent-Length: 0\r\n\r\n"
```

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +            await socket.sendBadRequestAndClose()
Looks like we can simplify this last part, now that you've improved the code:
```suggestion
        try:
            await callback(Request(
                client: socket,
                reqMethod: reqMethod,
                headers: headers,
                protocol: (orig: "HTTP/1." & $minorVersion, major: 1, minor: int(minorVersion)),
                url: parseUri(path), hostname: hostname, body: ""
            ))
        except ValueError:
            await socket.sendBadRequestAndClose()
```

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +    callback: proc (request: Request): Future[void] {.closure,gcsafe.},
Let's keep `callback` before `address`, because that's the order of arguments that `asynchttpserver.serve()` uses:
```suggestion
    callback: proc (request: Request): Future[void] {.closure,gcsafe.},
    address = "127.0.0.1",
```

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +            continue
TODO (for my own notes, you don't need to implement): Implement something like `server.maxFDs` and `shouldAcceptRequest()`, rather than unconditionally catching the `IOSelectorsException`: https://github.com/nim-lang/Nim/blob/version-1-6/lib/pure/asynchttpserver.nim#L389-L395

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +        return none[string]()
Let's get rid of this check. RFC 9110 specifies that for HTTP methods such as GET and HEAD "a client SHOULD NOT generate content ...": https://www.rfc-editor.org/rfc/rfc9110#name-method-definitions . So this can read the content of GET's and HEAD's, and leave it up to the application to interpret it.

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +    var body = newString(bodyLen)
`bodyLen` needs to have a server-specified max value, otherwise a client can OOM the server by specifying a ridiculous content length. I would recommend adding a parameter to this function named something like `maxBodyLen`, and only reading up to that many bytes. If the content length is beyond the max body len, don't read anything, complete the future with an exception.

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +    var buf: array[1024, char]
Make this a constant like `HTTP_HEADER_BUFFER_INITIAL_SIZE `.

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +        if bufLen == 0:
If the socket is unbuffered, `bufLen` can be zero if data is in transit, but hasn't arrived at the socket yet. This should only break early if bufLen is zero and the socket is closed.

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +            body[i + bodyReadPos] = buf[i]
Use `copyMem` instead.

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +        body.setLen(0)
`setLen` doesn't actually free the memory. If you want to free the memory, you have to reassign the string. 
```suggestion
    # If the body read position is less than the expected size, the client must have disconnected part-way through the read.
    # In that case, we'll free the memory that we've allocated, close the socket, and finally raise OSError.
    if bodyReadPos < bodyLen:
        body = ""
```

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +        raise newException(OSError, fmt"Client disconnected before full body could be read ({bodyReadPos}/{bodyLen} bytes read)")
I would raise `EOFError` instead.
```suggestion
        raise newException(EOFError, fmt"Client disconnected before full body could be read ({bodyReadPos}/{bodyLen} bytes read)")
```

2023-04-16 01:58 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +proc readBody*(req: Request): Future[Option[string]] {.async.} =
Would a `readBody` caller ever behave differently if the request had no `Content-Length` header, versus when `Content-Length` is zero? If not, we can return a `Future[string]` and just return an empty string for both of these cases.

2023-04-16 02:00 UTC, termermc commented on README.md
> -   [picohttpparser.c](https://github.com/h2o/picohttpparser/blob/master/picohttpparser.c).
Nimble. All you have to do is require it in your Nimble project and it should work fine. You can test it on my fork if you want to see how it works, but basically the project using it doesn't have to think about it anymore.

2023-04-16 02:04 UTC, termermc commented on src/microasynchttpserver.nim
> +    return res
It think it'd be best to use a ref object instead of a tuple. The syntax you showed doesn't compile for me:

```
Error: type mismatch: got 'AsyncSocket' for 'newAsyncSocket(AF_INET, SOCK_STREAM, IPPROTO_TCP, true, false)' but expected 'MicroAsyncHttpServer = ref tuple[socket: AsyncSocket]'
```

Changing it to a ref object also doesn't allow that syntax. I think it'd be best to leave it the way it is, but let me know what you think.

2023-04-16 02:05 UTC, termermc commented on src/microasynchttpserver.nim
> +    return res
Also, is there any benefit to using `result` here? I always thought it was way too implicit.

2023-04-16 02:06 UTC, termermc commented on src/microasynchttpserver.nim
> +    callback: proc (request: Request): Future[void] {.closure,gcsafe.},
My bad, should've looked at it first.

2023-04-16 02:08 UTC, termermc commented on src/microasynchttpserver.nim
> +        if bufLen == 0:
Good call. Let me update it.

2023-04-16 02:17 UTC, termermc commented on src/microasynchttpserver.nim
> +proc readBody*(req: Request): Future[Option[string]] {.async.} =
The difference between an empty body and no body is semantically different, and I'd rather let the end user know which is was for handling purposes. Nothing comes immediately to mind, but I'd rather not make it ambiguous and possibly make the end user manually check for a header, effectively requiring a second check when this proc already did one.

2023-04-16 02:25 UTC, termermc commented on src/microasynchttpserver.nim
> +        if bufLen == 0:
@philip-wernersbach Should work now, but I need to test whether it can detect when the client closes mid-stream

2023-04-16 02:28 UTC, termermc commented on src/microasynchttpserver.nim
> +        if bufLen == 0:
@philip-wernersbach It can't detect whether the client is closed or not, and therefore would leak memory because the proc Future would never get resolved. As far as I can tell, the only way to tell whether the socket is closed is by getting a 0 back. That's how recv on *nix works, not sure about Windows. But other servers like httpbeast also do a check for 0 to see if there's nothing left to read if I remember correctly.

2023-04-16 02:31 UTC, termermc commented on src/microasynchttpserver.nim
> +        if bufLen == 0:
I reverted it back to checking for a 0 for this reason

2023-04-16 02:31 UTC, termermc commented on src/microasynchttpserver.nim
> +            body[i + bodyReadPos] = buf[i]
Done

2023-04-16 05:53 UTC, philip-wernersbach requested changes
All that's left to do is make the changes for the unresolved conversations for the `readBody` proc, and this can be merged.

2023-04-16 05:53 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +    return res
1. The syntax might be `MicroAsyncHttpServer(socket: newAsyncSocket())`, but I can experiment to find the syntax so you don't have to spend time on this. Using this syntax does have an effect, I think @Araq wrote somewhere that it allows the compiler to do an "is this ref object initialized?" check.
2. Not sure if there's a benefit to using `result` specifically. Once I get the initialization syntax correct, I could change this to `return ...`, which avoids the implicit `result`.

2023-04-16 05:53 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +proc readBody*(req: Request): Future[Option[string]] {.async.} =
Fair enough. I'm not convinced that the distinction really matters to callers, but I'll trust your judgement here.

2023-04-16 05:53 UTC, philip-wernersbach commented on src/microasynchttpserver.nim
> +        if bufLen == 0:
Hmm okay. If other Nim HTTP servers also have this problem, then this warrants a discussion on the Nim Forums, as this is a somewhat prominent corner case. That's out of scope for this diff, so resolving this.

2023-04-16 05:57 UTC, termermc commented on src/microasynchttpserver.nim
> +    return res
@philip-wernersbach Switching it to a ref object and doing the normal constructor syntax worked

2023-04-16 06:00 UTC, termermc commented
> All that's left to do is make the changes for the unresolved conversations for the `readBody` proc, and this can be merged.

Just pushed a change for that

2023-04-16 14:41 UTC, philip-wernersbach approved these changes
Thank you for your contribution! This is great :smile:

2023-04-16 14:42 UTC, merged

2023-04-16 14:43 UTC, termermc commented
Happy to contribute. I'll be using this for some upcoming projects.

2023-04-16 14:45 UTC, philip-wernersbach commented
Squashed, merged, and tagged as 0.11.0. If you have any other changes you'd like to see to this, feel free to submit a PR!